					#####	Installing and loading required packages	#####

if (!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager")}
if(!require("derfinder")){BiocManager::install("derfinder")}
if(!require("derfinderData")){BiocManager::install("derfinderData")}
if(!require("GenomicRanges")){BiocManager::install("GenomicRanges")}
if(!require("EDASeq")){BiocManager::install("EDASeq")}
if(!require("DESeq2")){BiocManager::install("DESeq2")}
if(!require("SummarizedExperiment")){BiocManager::install("SummarizedExperiment")}
if(!require("Biobase")){BiocManager::install("Biobase")}
if(!require("DelayedArray")){BiocManager::install("DelayedArray")}
if(!require("BiocParallel")){BiocManager::install("BiocParallel")}
if(!require("matrixStats")){install.packages("matrixStats")}
if(!require("bumphunter")){BiocManager::install("bumphunter")}
if(!require("GenomeInfoDbData")){BiocManager::install("GenomeInfoDbData")}
if(!require("AnnotationDbi")){BiocManager::install("AnnotationDbi")}
if(!require("GenomicFeatures")){BiocManager::install("GenomicFeatures")}
if(!require("RSQLite")){install.packages("RSQLite")}
if(!require("rtracklayer")){BiocManager::install("rtracklayer")}
if(!require("dplyr")){install.packages("dplyr")}
if(!require("purrr")){install.packages("purrr")}
if(!require("ggplot2")){install.packages("ggplot2")}
if(!require("derfinderPlot")){BiocManager::install("derfinderPlot")}
if(!require("tidyr")){install.packages("tidyr")}
if(!require("GenomicAlignments")){BiocManager::install("GenomicAlignments")}
if(!require("RMySQL")){install.packages("RMySQL")}
if(!require("DBI")){install.packages("DBI")}
if(!require("devtools")){install.packages("devtools")}
if(!require("AnnotationHub")){BiocManager::install("AnnotationHub")}
if(!require("biomaRt")){BiocManager::install("biomaRt")}
if(!require("xml2")){install.packages("xml2")}
if(!require("curl")){install.packages("curl")}
if(!require("regionReport")){BiocManager::install("regionReport")}
if(!require("biovizBase")){BiocManager::install("biovizBase")}
if(!require("tidyverse")){install.packages("tidyverse")}
if(!require("knitr")){install.packages("knitr")}
if(!require("limma")){BiocManager::install("limma")}
if(!require("ensembldb")){BiocManager::install("ensembldb")}
if(!require("GOstats")){BiocManager::install("GOstats")}
if(!require("AnnotationForge")){BiocManager::install("AnnotationForge")}
if(!require("ggbio")){BiocManager::install("ggbio")}
if(!require("RMariaDB")){install.packages("RMariaDB")}
if(!require("rmarkdown")){install.packages("rmarkdown")}
if(!require("pryr")){install.packages("pryr")}
if(!require("furrr")){install.packages("furrr")}
if(!require("rstudioapi")){install.packages("rstudioapi")}
#if(!require("org.Oaries.eg.db")){BiocManager::install("org.Oaries.eg.db")}
