install.packages('derfinder')
install.packages('derfinderData')
install.packages('GenomicRanges')
install.packages('EDASeq')
install.packages("DESeq2")
install.packages("SummarizedExperiment")
install.packages("Biobase")
install.packages("DelayedArray")
install.packages("matrixStats")
install.packages("BiocParallel")
install.packages("bumphunter")
install.packages("GenomeInfoDbData")
install.packages("AnnotationDbi")
install.packages("GenomicFeatures")
install.packages("RSQLite")
install.packages("rtracklayer")
install.packages("dplyr")
install.packages("purrr")
install.packages("ggplot2")
install.packages("derfinderPlot")
install.packages("tidyr")
install.packages("GenomicAlignments")#
install.packages("RMySQL")
install.packages("DBI")
install.packages("devtools")#
install.packages("AnnotationHub")#
install.packages("biomaRt")
install.packages('xml2')
install.packages('curl')#
install.packages("regionReport")
install.packages("biovizBase")#
install.packages("tidyverse")
install.packages("knitr")
install.packages("limma")
install.packages("ensembldb")
install.packages("AnnotationHub")
install.packages("GOstats")
install.packages("AnnotationForge")
install.packages("org.Oaries.eg.db")#????????????????
install.packages("ggbio")
install.packages("RMariaDB")
install.packages("rmarkdown")
install.packages("pryr")
install.packages("furrr")
install.packages("rstudioapi")


#