if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("derfinder")

install.packages("devtools")
install.packages("Matrix")
install.packages("ggplot2")
install.packages("mgcv")
install.packages("survival")
install.packages("foreign")
install.packages("rpart")
install.packages("codetools")
